# /config.yml
chatbot:
  name: "AGENT_FRAMEWORK"
Key_File: "../key.env"
OpenAI:
  chat_temp: 0.0
  llm_temp: 0.0
  openai_api_type: "azure"
  model: "gpt-4"
  model_32k: "gpt-4-32k"
  deployment_name: "gpt-4"
  deployment_name_32k: "gpt-4-32k"
  model_version: "0613"
  openai_api_version: "2023-07-01-preview"
  openai_api_base: https://techmodaitest.openai.azure.com/
  embedding_model_name: "text-embedding-ada-002"
  embedding_model_deployment_name: "text-embedding-ada-002"
  text_summary_deployment_name: "gpt-35-turbo"
  text_summary_model: "gpt-35-turbo"
  text_summary_model_version: "0301"
Logging:
  level: INFO
Scraper:
  DATA_DIR: './src/scraper/scraped_data'
  USER_AGENTS:
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.82 Safari/537.36"
    - "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Firefox/89.0"
    - "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
Qdrant:
  url: "AGENT_FRAMEWORK_QDRANT"
  vector_size: "1536"
  logging_level: "DEBUG"
Phoenix:
  endpoint: "http://AGENT_FRAMEWORK_PHOENIX:6006"
